sudo: required
language: generic
env:
  global:
    - JOB_NAME=limited-build
matrix:
  include:
    - os: linux
      dist: trusty
      env:
        - CXX=g++
        - NODE_LABELS="Linux Ubuntu Ubuntu-14.04"
    - os: linux
      dist: trusty
      env:
        - CXX=clang++
        - NODE_LABELS="Linux Ubuntu Ubuntu-14.04"
    - os: osx
      env:
        - CXX=clang++
        - NODE_LABELS="OSX OSX-10.9"
notifications:
  email:
    on_success: always
    on_failure: always
script:
  - ./.jenkins
